module: BluetoothKit                  # 모듈명 정확히 일치시켜야 symbol 인식됨
swift_build_tool: spm                # SwiftPM 프로젝트임을 명시
output: docs/ios-jazzy               # Docusaurus용 경로로 명시
min_acl: public                      # public만 문서화, internal/private 제외
theme: apple                         # UI 스타일 선택
exclude: Tests                       # 테스트 파일 무시

# 메타데이터
author: BluetoothKit SDK             # 작성자/프로젝트명
author_url: https://github.com/Jackorea/IOS_link_band_sdk.git  # 프로젝트 URL (실제 URL로 수정 필요)
module_version: 1.0.0                # 버전 정보
copyright: '© 2024 BluetoothKit SDK. All rights reserved.'  # 저작권 정보
title: "BluetoothKit SDK Documentation"  # 문서 제목

# 문서 품질 설정
clean: true                          # 이전 문서 삭제 후 새로 생성
skip_undocumented: false             # 문서화되지 않은 항목도 포함 (완성도 확인용)
hide_documentation_coverage: false   # 문서화 커버리지 표시
readme: README.md                    # README 파일 포함 (파일이 있다면)
